version: "3.9"

services:
  temp-logger:
    image: ghcr.io/mattihayes/pi-logger:latest
    container_name: temp-logger
    ports:
      - "5000:5000"
    volumes:
      - /sys:/sys
    environment:
      - USE_MOCK_SENSORS=false
    restart: always