name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4

    - name: log into Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase owner
      run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

          
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{  env.REPO_OWNER_LC  }}/pi-logger:latest
